### ISSUE TITLE
thx + help

### ISSUE THREAD

**Issue by TonTonSheitan** [ig0ne/esx_Info-Shop#1]
Salut ig0ne, Merci pour ce script c'est sympa.

-J'aurai une questions a te poser j'ai ce script la https://github.com/Cha0sNighT/depanneur mais bien-sur il fonctionne avec jobsysteme, tu crois qui aurait une solution facile et rapide pour le faire fonctionner avec les script esx_... ??

Mercii pour ta réponse.

Cordialement

**Comment by ig0ne** [comment]
je jetterais un oeil mais je te promet rien

**Comment by TonTonSheitan** [comment]
oui ya pas de souci ;)

Et dis a tu le même problème que moi : 

Quand plusieurs personne font spawn le véhicule de fonction( pecheur ...)  certains vehicule despawn comme par magie et quand il acheté un véhicule au carshop il despawn aussi. J'utilise les script de esx_... pour le carshop et les metier.

Aurait tu le même problème ou entendu des personnes parler de ça ? 

PS: Désoler de te déranger avec sa lol Mercii

**Comment by ig0ne** [comment]
oui j'ai eu les mêmes soucis de despawn

**Comment by TonTonSheitan** [comment]
tu as pas de solutions a ce probléme ?

**Comment by ig0ne** [comment]
non pas pour le moment

**Comment by ig0ne** [comment]
Pour le dépanneur j'ai regardé vite fais mais je pourrais pas le rendre compatible par contre je pourrais (pas de suite) m'en inspirer pour en faire un compatible ESX. Sinon pour le problème de despawn il y a un sujet ouvert sur le github d'Indilo https://github.com/indilo53/fivem-es_extended/issues/31
